debug: false

flush:
  disable: false
  interval: 30
restore:
  disable: false
  interval: 300 #5 minutes
  jobSize: 1000

tables:
  blocks: MiracleGrow_%s_blocks
  jobs: MiracleGrow_%s_jobs

